name: Sync fork with upstream

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_repository: Thysrael/Horizon
          upstream_branch: main
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
